---
squash: false
build_from:
  arm64: ausrastor/barcodebuddy:latest
  aarch64: ausrastor/barcodebuddy:latest
  amd64: ausrastor/barcodebuddy:latest
  armv7: ausrastor/barcodebuddy:latest
  i386: ausrastor/barcodebuddy:latest
args: {}
